input {
  beats {
    port => 5044
  }
}

filter {
  grok {
    match => { "message" => "%{TIMESTAMP_ISO8601:timestamp} %{NOTSPACE:logger} %{LOGLEVEL:log_level} %{GREEDYDATA:event_message}" }
  }
  
  if [event_message] =~ /New connection/ {
    grok {
      match => { "event_message" => "New connection: %{IP:source_ip}:%{NUMBER:source_port} %{GREEDYDATA:connection_details}" }
      tag_on_failure => []
    }
  }
  
  if [event_message] =~ /login attempt/ {
    grok {
      match => { "event_message" => "login attempt \[%{DATA:username}/%{DATA:password}\] %{GREEDYDATA:login_details}" }
      tag_on_failure => []
    }
  }
  
  if [event_message] =~ /CMD:/ {
    grok {
      match => { "event_message" => "CMD: %{GREEDYDATA:command}" }
      tag_on_failure => []
    }
  }
  
  date {
    match => ["timestamp", "ISO8601"]
    target => "@timestamp"
  }
}

output {
  elasticsearch {
    hosts => ["http://elasticsearch:9200"]
    index => "honeypot-logs-%{+YYYY.MM.dd}"
  }
  stdout { codec => rubydebug }
}
